### ISSUE TITLE
Arreglar errores generales

### ISSUE THREAD

**Issue by noemigportillo** [noemigportillo/laravel-docker-CryptoAPI-src#26]
# ToDo
- [x] Cambiar nombre BuyCoinServiceTest1
- [x] Poner tests de servicios todos en el mismo sitio.
- [x] Hay que utilizar el AppServiceProvider (problemas con la inyección de dependencias)
- [x] Borrar líneas innecesarias.

**Comment by noemigportillo** [comment]
Se ha reabierto el issue para:
- [ ] Arreglar la integración contínua -> Se ha hecho reabriendo el issue https://github.com/noemigportillo/laravel-docker-CryptoAPI-src/issues/21+
- [ ] Crear algunas carpetas para mejorar la uniformidad.
